server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name <domain.name>;

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name <domain.name>;

        ssl_certificate /etc/letsencrypt/live/<cert.name>/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/<cert.name>/privkey.pem;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location /api/ {
                proxy_pass http://localhost:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
        }
         
        location / {
                root /dir/to/project/dist;
                try_files $uri /index.html;
        }
}



